name: Sinsata Visuals ni qurish

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Kodni olish
        uses: actions/checkout@v4

      - name: Java 21 ni o'rnatish
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Gradle-ni sozlash
        uses: gradle/actions/setup-gradle@v4

      - name: Gradle wrapper yaratish
        run: gradle wrapper --gradle-version 8.8

      - name: Mod-ni qurish
        run: ./gradlew build --no-daemon

      - name: Tayyor .jar faylni yuklash
        uses: actions/upload-artifact@v4
        with:
          name: SinsataVisuals-jar
          path: build/libs/*.jar
